# Generated by Django 3.0.3 on 2020-07-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=16)),
                ('salt', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
    ]
